language: ruby
rvm:
  - 2.3.1
before_script:
  - git clone https://github.com/moshe-immerman/awesome_bot.git && cd awesome_bot
  - gem build awesome_bot.gemspec
  - gem install awesome_bot*.gem http
script:
  - git diff master..`git rev-parse --abbrev-ref HEAD` README.md | grep + > CHANGED.md
  - awesome_bot CHANGED.md --github-age 500
  - awesome_bot README.md --white-list wiki/Installing,slideshare,awesome-docker.svg,edit/master,sindresorhus/awesome,ashmckenzie,shortcircuit.net.au,photo777.org,adrianmouat,redhat,viget,meros,toedter,datadoghq,amazon.cn,blog.codeship.com,swarm-v-fleet,amazon.com,blogs.splunk.com,docs.mesosphere.com,containership.io,gliderlabs.com,twistlock.com,shipyard-project.com,dashboard.tutum.co,vimeo.com,docs.microsoft.com,eclipse.org,codenvy.io,gitter.im,sebgoa.blogspot.be,mindmeister.com